/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SocialPost {
  body: string | null;
  data?: {
    [k: string]: unknown;
  } | null;
  title?: string | null;
  master?: string | null;
  context?: string | null;
  mentions?:
    | {
        did: string;
        username: string;
        [k: string]: unknown;
      }[]
    | null;
  reply_to?: string | null;
  encryptedBody?: {
    encryptedString?: string;
    encryptedSymmetricKey?: string;
    accessControlConditions?: string;
    [k: string]: unknown;
  } | null;
  media?:
    | {
        url: string;
        title?: string | null;
        gateway?: string | null;
        [k: string]: unknown;
      }[]
    | null;
  tags?:
    | {
        slug: string;
        title?: string | null;
        [k: string]: unknown;
      }[]
    | null;
  sourceUrl?: string | null;
  [k: string]: unknown;
}

export interface SocialGroup {
  pfp?: string | null;
  data?: {
    [k: string]: unknown;
  } | null;
  name: string;
  description?: string | null;
  [k: string]: unknown;
}

export interface SocialProject {
  name: string;
  website?: string | null;
  pfp?: string | null;
  description?: string | null;
  [k: string]: unknown;
}

export interface SocialContext {
  name: string;
  context?: string | null;
  project_id?: string | null;
  websiteUrl?: string | null;
  accessRules?:
    | {
        type?: string;
        operator?: string | null;
        authorizedUsers?:
          | {
              did?: string;
              [k: string]: unknown;
            }[]
          | null;
        requiredCredentials?:
          | {
              identifier?: string;
              [k: string]: unknown;
            }[]
          | null;
        [k: string]: unknown;
      }[]
    | null;
  displayName?: string | null;
  integrations?: {
    discord?: {
      channel_id?: string;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  } | null;
  pfp?: string | null;
  description?: string | null;
  [k: string]: unknown;
}

export interface SocialProfile {
  pfp?: string | null;
  data?: {
    [k: string]: unknown;
  } | null;
  cover?: string | null;
  pfpIsNft?: {
    chain?: string;
    tokenId?: string;
    contract?: string;
    timestamp?: string;
    [k: string]: unknown;
  } | null;
  username?: string | null;
  description?: string | null;
  [k: string]: unknown;
}

export interface SocialEncryptedEmail {
  encryptedEmail?: {
    encryptedString?: string;
    encryptedSymmetricKey?: string;
    accessControlConditions?: string;
    [k: string]: unknown;
  } | null;
  [k: string]: unknown;
}

export interface SocialReaction {
  type: string;
  post_id: string;
  [k: string]: unknown;
}

export interface SocialFollow {
  did: string;
  active: boolean;
  [k: string]: unknown;
}

export interface SocialConversation {
  name?: string | null;
  context?: string | null;
  recipients: string[];
  description?: string | null;
  [k: string]: unknown;
}

export interface SocialPrivateMessage {
  master?: string | null;
  reply_to?: string | null;
  conversation_id: string;
  encryptedMessage?: {
    encryptedString?: string;
    encryptedSymmetricKey?: string;
    accessControlConditions?: string;
    [k: string]: unknown;
  } | null;
  encryptedMessageSolana?: {
    encryptedString?: string;
    solRpcConditions?: string;
    encryptedSymmetricKey?: string;
    [k: string]: unknown;
  } | null;
  [k: string]: unknown;
}

export interface SocialSettingsNotificationsRead {
  last_notifications_read_time: number;
  [k: string]: unknown;
}
